var annotated_dup =
[
    [ "farm_ng", "namespacefarm__ng.html", [
      [ "plotting", "namespacefarm__ng_1_1plotting.html", [
        [ "ClearCondition", "structfarm__ng_1_1plotting_1_1_clear_condition.html", "structfarm__ng_1_1plotting_1_1_clear_condition" ],
        [ "ColoredRect", "structfarm__ng_1_1plotting_1_1_colored_rect.html", "structfarm__ng_1_1plotting_1_1_colored_rect" ]
      ] ],
      [ "testing", "namespacefarm__ng_1_1testing.html", [
        [ "CaptureStdErr", "classfarm__ng_1_1testing_1_1_capture_std_err.html", "classfarm__ng_1_1testing_1_1_capture_std_err" ]
      ] ],
      [ "time_series", "namespacefarm__ng_1_1time__series.html", [
        [ "MaxGap", "structfarm__ng_1_1time__series_1_1_max_gap.html", "structfarm__ng_1_1time__series_1_1_max_gap" ],
        [ "NearnessThreshold", "structfarm__ng_1_1time__series_1_1_nearness_threshold.html", "structfarm__ng_1_1time__series_1_1_nearness_threshold" ]
      ] ],
      [ "Error", "structfarm__ng_1_1_error.html", "structfarm__ng_1_1_error" ],
      [ "Success", "structfarm__ng_1_1_success.html", null ],
      [ "StreamLogger", "classfarm__ng_1_1_stream_logger.html", "classfarm__ng_1_1_stream_logger" ],
      [ "ErrorDetail", "structfarm__ng_1_1_error_detail.html", "structfarm__ng_1_1_error_detail" ],
      [ "Shared", "classfarm__ng_1_1_shared.html", "classfarm__ng_1_1_shared" ],
      [ "StopwatchSingleton", "classfarm__ng_1_1_stopwatch_singleton.html", "classfarm__ng_1_1_stopwatch_singleton" ],
      [ "ScopedTimer", "structfarm__ng_1_1_scoped_timer.html", "structfarm__ng_1_1_scoped_timer" ],
      [ "TimeSeries", "classfarm__ng_1_1_time_series.html", "classfarm__ng_1_1_time_series" ],
      [ "Uri", "structfarm__ng_1_1_uri.html", "structfarm__ng_1_1_uri" ],
      [ "Overload", "structfarm__ng_1_1_overload.html", null ],
      [ "HasType", "structfarm__ng_1_1_has_type.html", null ],
      [ "HasType< T, std::variant< Us... > >", "structfarm__ng_1_1_has_type_3_01_t_00_01std_1_1variant_3_01_us_8_8_8_01_4_01_4.html", null ],
      [ "Void", "structfarm__ng_1_1_void.html", null ],
      [ "Component", "classfarm__ng_1_1_component.html", "classfarm__ng_1_1_component" ],
      [ "Input", "classfarm__ng_1_1_input.html", "classfarm__ng_1_1_input" ],
      [ "Output", "classfarm__ng_1_1_output.html", "classfarm__ng_1_1_output" ],
      [ "Context", "classfarm__ng_1_1_context.html", "classfarm__ng_1_1_context" ],
      [ "ContextStrand", "classfarm__ng_1_1_context_strand.html", "classfarm__ng_1_1_context_strand" ],
      [ "InputConfig", "classfarm__ng_1_1_input_config.html", "classfarm__ng_1_1_input_config" ],
      [ "ThreadPool", "classfarm__ng_1_1_thread_pool.html", "classfarm__ng_1_1_thread_pool" ],
      [ "PlottingComponent", "classfarm__ng_1_1_plotting_component.html", "classfarm__ng_1_1_plotting_component" ],
      [ "RemotePlottingClient", "classfarm__ng_1_1_remote_plotting_client.html", "classfarm__ng_1_1_remote_plotting_client" ],
      [ "ToProtoTrait< sophus::IntensityImage<> >", "structfarm__ng_1_1_to_proto_trait_3_01sophus_1_1_intensity_image_3_4_01_4.html", "structfarm__ng_1_1_to_proto_trait_3_01sophus_1_1_intensity_image_3_4_01_4" ],
      [ "FromProtImpl", "structfarm__ng_1_1_from_prot_impl.html", null ],
      [ "ToProtImpl", "structfarm__ng_1_1_to_prot_impl.html", null ],
      [ "ToProtoTrait", "structfarm__ng_1_1_to_proto_trait.html", null ],
      [ "FromProtoTrait", "structfarm__ng_1_1_from_proto_trait.html", null ],
      [ "EventLogExist", "classfarm__ng_1_1_event_log_exist.html", "classfarm__ng_1_1_event_log_exist" ],
      [ "EventLogReaderBase", "structfarm__ng_1_1_event_log_reader_base.html", "structfarm__ng_1_1_event_log_reader_base" ],
      [ "EventLogPos", "classfarm__ng_1_1_event_log_pos.html", "classfarm__ng_1_1_event_log_pos" ],
      [ "EventLogReader", "classfarm__ng_1_1_event_log_reader.html", "classfarm__ng_1_1_event_log_reader" ],
      [ "EventTimeCompareClockAndSemantics", "structfarm__ng_1_1_event_time_compare_clock_and_semantics.html", "structfarm__ng_1_1_event_time_compare_clock_and_semantics" ],
      [ "EventLogWriter", "classfarm__ng_1_1_event_log_writer.html", "classfarm__ng_1_1_event_log_writer" ]
    ] ],
    [ "sophus", "namespacesophus.html", [
      [ "concepts", "namespacesophus_1_1concepts.html", [
        [ "details", "namespacesophus_1_1concepts_1_1details.html", [
          [ "Reduce", "classsophus_1_1concepts_1_1details_1_1_reduce.html", "classsophus_1_1concepts_1_1details_1_1_reduce" ],
          [ "Reduce< TT >", "classsophus_1_1concepts_1_1details_1_1_reduce_3_01_t_t_01_4.html", null ]
        ] ],
        [ "UnitVector", "classsophus_1_1concepts_1_1_unit_vector.html", null ],
        [ "CompatScalarEx", "structsophus_1_1concepts_1_1_compat_scalar_ex.html", "structsophus_1_1concepts_1_1_compat_scalar_ex" ]
      ] ],
      [ "detail", "namespacesophus_1_1detail.html", [
        [ "VisitImpl", "structsophus_1_1detail_1_1_visit_impl.html", null ],
        [ "VisitImpl< TUserFunc, TDynImage, std::variant< TPixelFormat > >", "structsophus_1_1detail_1_1_visit_impl_3_01_t_user_func_00_01_t_dyn_image_00_01std_1_1variant_3_01_t_pixel_format_01_4_01_4.html", null ],
        [ "VisitImpl< TUserFunc, TDynImage, std::variant< TPixelFormat, TRest... > >", "structsophus_1_1detail_1_1_visit_impl_3_01_t_user_func_00_01_t_dyn_image_00_01std_1_1variant_3_0d99d88b250f274dea348c380a7d77c77.html", null ]
      ] ],
      [ "jet_helpers", "namespacesophus_1_1jet__helpers.html", [
        [ "GetValue", "structsophus_1_1jet__helpers_1_1_get_value.html", null ]
      ] ],
      [ "lie", "namespacesophus_1_1lie.html", [
        [ "IdentityImpl", "classsophus_1_1lie_1_1_identity_impl.html", "classsophus_1_1lie_1_1_identity_impl" ],
        [ "IdentityWithDim", "structsophus_1_1lie_1_1_identity_with_dim.html", "structsophus_1_1lie_1_1_identity_with_dim" ],
        [ "Rotation2Impl", "classsophus_1_1lie_1_1_rotation2_impl.html", "classsophus_1_1lie_1_1_rotation2_impl" ],
        [ "Rotation3Impl", "classsophus_1_1lie_1_1_rotation3_impl.html", "classsophus_1_1lie_1_1_rotation3_impl" ],
        [ "ScalingImpl", "classsophus_1_1lie_1_1_scaling_impl.html", "classsophus_1_1lie_1_1_scaling_impl" ],
        [ "ScalingWithDim", "structsophus_1_1lie_1_1_scaling_with_dim.html", "structsophus_1_1lie_1_1_scaling_with_dim" ],
        [ "SpiralSimilarity2Impl", "classsophus_1_1lie_1_1_spiral_similarity2_impl.html", "classsophus_1_1lie_1_1_spiral_similarity2_impl" ],
        [ "SpiralSimilarity3Impl", "classsophus_1_1lie_1_1_spiral_similarity3_impl.html", "classsophus_1_1lie_1_1_spiral_similarity3_impl" ],
        [ "TranslationFactorGroupProduct", "classsophus_1_1lie_1_1_translation_factor_group_product.html", "classsophus_1_1lie_1_1_translation_factor_group_product" ],
        [ "WithDimAndSubgroup", "structsophus_1_1lie_1_1_with_dim_and_subgroup.html", "structsophus_1_1lie_1_1_with_dim_and_subgroup" ],
        [ "Group", "classsophus_1_1lie_1_1_group.html", "classsophus_1_1lie_1_1_group" ],
        [ "ScalingTranslationWithDim", "structsophus_1_1lie_1_1_scaling_translation_with_dim.html", "structsophus_1_1lie_1_1_scaling_translation_with_dim" ],
        [ "TranslationWithDim", "structsophus_1_1lie_1_1_translation_with_dim.html", "structsophus_1_1lie_1_1_translation_with_dim" ]
      ] ],
      [ "linalg", "namespacesophus_1_1linalg.html", [
        [ "UnitVectorImpl", "classsophus_1_1linalg_1_1_unit_vector_impl.html", "classsophus_1_1linalg_1_1_unit_vector_impl" ]
      ] ],
      [ "test", "namespacesophus_1_1test.html", [
        [ "DivisionRingTestSuite", "structsophus_1_1test_1_1_division_ring_test_suite.html", "structsophus_1_1test_1_1_division_ring_test_suite" ],
        [ "LieGroupPropTestSuite", "structsophus_1_1test_1_1_lie_group_prop_test_suite.html", "structsophus_1_1test_1_1_lie_group_prop_test_suite" ],
        [ "ManifoldPropTestSuite", "structsophus_1_1test_1_1_manifold_prop_test_suite.html", "structsophus_1_1test_1_1_manifold_prop_test_suite" ]
      ] ],
      [ "Region", "classsophus_1_1_region.html", "classsophus_1_1_region" ],
      [ "Mapper", "structsophus_1_1_mapper.html", "structsophus_1_1_mapper" ],
      [ "Mapper< TScalar, typename std::enable_if< kIsMappableV< TScalar > >::type >", "structsophus_1_1_mapper_3_01_t_scalar_00_01typename_01std_1_1enable__if_3_01k_is_mappable_v_3_01cd5529748b13d40e64d4c3ee260777da.html", "structsophus_1_1_mapper_3_01_t_scalar_00_01typename_01std_1_1enable__if_3_01k_is_mappable_v_3_01cd5529748b13d40e64d4c3ee260777da" ],
      [ "Color", "structsophus_1_1_color.html", "structsophus_1_1_color" ],
      [ "UninitTag", "structsophus_1_1_uninit_tag.html", null ],
      [ "IsUniformRandomBitGenerator", "structsophus_1_1_is_uniform_random_bit_generator.html", null ],
      [ "Complex", "classsophus_1_1_complex.html", "classsophus_1_1_complex" ],
      [ "Quaternion", "classsophus_1_1_quaternion.html", "classsophus_1_1_quaternion" ],
      [ "UnitVector", "classsophus_1_1_unit_vector.html", "classsophus_1_1_unit_vector" ],
      [ "InverseDepthPoint3", "classsophus_1_1_inverse_depth_point3.html", "classsophus_1_1_inverse_depth_point3" ],
      [ "PointTransformer", "classsophus_1_1_point_transformer.html", "classsophus_1_1_point_transformer" ],
      [ "Ray", "classsophus_1_1_ray.html", "classsophus_1_1_ray" ],
      [ "ClosestApproachResult", "structsophus_1_1_closest_approach_result.html", "structsophus_1_1_closest_approach_result" ],
      [ "DynImage", "classsophus_1_1_dyn_image.html", "classsophus_1_1_dyn_image" ],
      [ "IntensityImagePredicate", "structsophus_1_1_intensity_image_predicate.html", "structsophus_1_1_intensity_image_predicate" ],
      [ "AnyImagePredicate", "structsophus_1_1_any_image_predicate.html", null ],
      [ "DynImageView", "classsophus_1_1_dyn_image_view.html", "classsophus_1_1_dyn_image_view" ],
      [ "Image", "classsophus_1_1_image.html", "classsophus_1_1_image" ],
      [ "ImageSize", "structsophus_1_1_image_size.html", "structsophus_1_1_image_size" ],
      [ "ImageTraits", "structsophus_1_1_image_traits.html", "structsophus_1_1_image_traits" ],
      [ "MutImage", "classsophus_1_1_mut_image.html", "classsophus_1_1_mut_image" ],
      [ "ImageView", "structsophus_1_1_image_view.html", "structsophus_1_1_image_view" ],
      [ "ImageLayout", "classsophus_1_1_image_layout.html", "classsophus_1_1_image_layout" ],
      [ "MutDynImage", "classsophus_1_1_mut_dyn_image.html", "classsophus_1_1_mut_dyn_image" ],
      [ "MutDynImageView", "classsophus_1_1_mut_dyn_image_view.html", "classsophus_1_1_mut_dyn_image_view" ],
      [ "UniqueDataAreaDeleter", "structsophus_1_1_unique_data_area_deleter.html", "structsophus_1_1_unique_data_area_deleter" ],
      [ "MaybeLeakingUniqueDataAreaDeleter", "structsophus_1_1_maybe_leaking_unique_data_area_deleter.html", "structsophus_1_1_maybe_leaking_unique_data_area_deleter" ],
      [ "MutImageView", "classsophus_1_1_mut_image_view.html", "classsophus_1_1_mut_image_view" ],
      [ "PixelFormat", "structsophus_1_1_pixel_format.html", "structsophus_1_1_pixel_format" ],
      [ "CubicBSplineImpl", "classsophus_1_1_cubic_b_spline_impl.html", "classsophus_1_1_cubic_b_spline_impl" ],
      [ "CubicBSpline", "classsophus_1_1_cubic_b_spline.html", "classsophus_1_1_cubic_b_spline" ],
      [ "SegmentCoordinate", "structsophus_1_1_segment_coordinate.html", "structsophus_1_1_segment_coordinate" ],
      [ "CubicLieGroupBSplineFn", "classsophus_1_1_cubic_lie_group_b_spline_fn.html", "classsophus_1_1_cubic_lie_group_b_spline_fn" ],
      [ "CubicLieGroupBSplineImpl", "classsophus_1_1_cubic_lie_group_b_spline_impl.html", "classsophus_1_1_cubic_lie_group_b_spline_impl" ],
      [ "CubicLieGroupBSpline", "classsophus_1_1_cubic_lie_group_b_spline.html", "classsophus_1_1_cubic_lie_group_b_spline" ],
      [ "GroupManifold", "structsophus_1_1_group_manifold.html", "structsophus_1_1_group_manifold" ],
      [ "Identity", "classsophus_1_1_identity.html", "classsophus_1_1_identity" ],
      [ "Scaling", "classsophus_1_1_scaling.html", "classsophus_1_1_scaling" ],
      [ "Isometry2", "classsophus_1_1_isometry2.html", "classsophus_1_1_isometry2" ],
      [ "Isometry3", "classsophus_1_1_isometry3.html", "classsophus_1_1_isometry3" ],
      [ "Pose3", "classsophus_1_1_pose3.html", "classsophus_1_1_pose3" ],
      [ "Rotation2", "classsophus_1_1_rotation2.html", "classsophus_1_1_rotation2" ],
      [ "Rotation3", "classsophus_1_1_rotation3.html", "classsophus_1_1_rotation3" ],
      [ "ScalingTranslation", "classsophus_1_1_scaling_translation.html", "classsophus_1_1_scaling_translation" ],
      [ "Similarity2", "classsophus_1_1_similarity2.html", "classsophus_1_1_similarity2" ],
      [ "Similarity3", "classsophus_1_1_similarity3.html", "classsophus_1_1_similarity3" ],
      [ "SpiralSimilarity2", "classsophus_1_1_spiral_similarity2.html", "classsophus_1_1_spiral_similarity2" ],
      [ "SpiralSimilarity3", "classsophus_1_1_spiral_similarity3.html", "classsophus_1_1_spiral_similarity3" ],
      [ "Translation", "classsophus_1_1_translation.html", "classsophus_1_1_translation" ],
      [ "PointTraits", "structsophus_1_1_point_traits.html", null ],
      [ "PointTraits< TPoint >", "structsophus_1_1_point_traits_3_01_t_point_01_4.html", "structsophus_1_1_point_traits_3_01_t_point_01_4" ],
      [ "ComplexImpl", "classsophus_1_1_complex_impl.html", "classsophus_1_1_complex_impl" ],
      [ "ProductManifold", "classsophus_1_1_product_manifold.html", "classsophus_1_1_product_manifold" ],
      [ "QuaternionImpl", "classsophus_1_1_quaternion_impl.html", "classsophus_1_1_quaternion_impl" ],
      [ "VectorManifold", "structsophus_1_1_vector_manifold.html", "structsophus_1_1_vector_manifold" ],
      [ "AffineTransform", "classsophus_1_1_affine_transform.html", "classsophus_1_1_affine_transform" ],
      [ "BrownConradyTransform", "classsophus_1_1_brown_conrady_transform.html", "classsophus_1_1_brown_conrady_transform" ],
      [ "KannalaBrandtK3Transform", "classsophus_1_1_kannala_brandt_k3_transform.html", "classsophus_1_1_kannala_brandt_k3_transform" ],
      [ "CameraModelT", "classsophus_1_1_camera_model_t.html", "classsophus_1_1_camera_model_t" ],
      [ "CameraModel", "classsophus_1_1_camera_model.html", "classsophus_1_1_camera_model" ],
      [ "ProjectionOrtho", "structsophus_1_1_projection_ortho.html", "structsophus_1_1_projection_ortho" ],
      [ "ProjectionZ1", "structsophus_1_1_projection_z1.html", "structsophus_1_1_projection_z1" ],
      [ "RigidCamera", "structsophus_1_1_rigid_camera.html", "structsophus_1_1_rigid_camera" ],
      [ "ClippingPlanes", "structsophus_1_1_clipping_planes.html", "structsophus_1_1_clipping_planes" ],
      [ "ScalingNonOrthogonalityGyroModel", "structsophus_1_1_scaling_non_orthogonality_gyro_model.html", "structsophus_1_1_scaling_non_orthogonality_gyro_model" ],
      [ "ScalingNonOrthogonalityAcceleroModel", "structsophus_1_1_scaling_non_orthogonality_accelero_model.html", "structsophus_1_1_scaling_non_orthogonality_accelero_model" ],
      [ "ImuModel", "classsophus_1_1_imu_model.html", "classsophus_1_1_imu_model" ]
    ] ]
];